export const SUBSCRIPTION_PLANS = [
  {
    id: "starter",
    name: "Starter",
    tagline: "For small cafés, food trucks & single counters",
    priceMonthly: 999,
    priceYearly: 799,
    popular: false,
    badge: null,
    buttonText: "Start 14-Day Free Trial",
    features: [
      "1 POS Counter",
      "Up to 150 Menu Items",
      "Fast Billing & GST Invoicing",
      "2-Inch & 3-Inch Thermal Printing",
      "Basic Sales Reporting",
      "Standard Email Support",
    ],
  },
  {
    id: "business-pro",
    name: "Business Pro",
    tagline: "For full-service restaurants, bars & diners",
    priceMonthly: 1999,
    priceYearly: 1599,
    popular: true,
    badge: "MOST POPULAR",
    buttonText: "Get Started Now",
    features: [
      "Unlimited POS Counters",
      "Unlimited Menu Items & Categories",
      "Live Table Occupancy & Seating",
      "KOT & Kitchen Queue Management",
      "GST Calculation & Custom Discounts",
      "Advanced Sales Analytics & Peak Hours",
      "Multi-User Staff & Admin Permissions",
      "Priority 24/7 Phone & Chat Support",
    ],
  },
  {
    id: "multi-outlet",
    name: "Enterprise Multi-Outlet",
    tagline: "For restaurant chains, franchises & large venues",
    priceMonthly: 3999,
    priceYearly: 3199,
    popular: false,
    badge: "ENTERPRISE",
    buttonText: "Contact Sales Team",
    features: [
      "Multi-Branch & Franchise Management",
      "Centralized Inventory & Stock Control",
      "Custom Thermal & A4 Print Layouts",
      "CSV Bulk Import / Export Data",
      "Dedicated Account Success Manager",
      "Custom API Integration & Webhooks",
    ],
  },
];
